# Generated by Django 4.1.13 on 2024-08-15 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisers',
            options={'verbose_name': 'Рекламодатель', 'verbose_name_plural': 'Рекламодатели'},
        ),
        migrations.AlterModelOptions(
            name='balances',
            options={'verbose_name': 'Баланс', 'verbose_name_plural': 'Балансы'},
        ),
        migrations.AlterModelOptions(
            name='characters',
            options={'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='gamekeys',
            options={'verbose_name': 'Игровой ключ', 'verbose_name_plural': 'Игровые ключи'},
        ),
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='tariffs',
            options={'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterModelOptions(
            name='wallets',
            options={'verbose_name': 'Кошелек', 'verbose_name_plural': 'Кошельки'},
        ),
        migrations.AlterField(
            model_name='advertisers',
            name='payment_date',
            field=models.DateTimeField(verbose_name='Дата и время оплаты'),
        ),
        migrations.AlterField(
            model_name='advertisers',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tariffs', verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='advertisers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='balances',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество монет'),
        ),
        migrations.AlterField(
            model_name='balances',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='characters',
            name='multiplier',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Множитель заработка'),
        ),
        migrations.AlterField(
            model_name='characters',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='characters',
            name='price_stars',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в Stars'),
        ),
        migrations.AlterField(
            model_name='characters',
            name='price_ton',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в TON'),
        ),
        migrations.AlterField(
            model_name='characters',
            name='type',
            field=models.CharField(choices=[('standart', 'Новичок'), ('silver', 'Опытный'), ('gold', 'Легенда')], max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.characters', verbose_name='Персонаж'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Реферальный код'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пригласил'),
        ),
        migrations.AlterField(
            model_name='gamekeys',
            name='value',
            field=models.CharField(max_length=255, unique=True, verbose_name='Значение ключа'),
        ),
        migrations.AlterField(
            model_name='games',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='games',
            name='link',
            field=models.CharField(max_length=255, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='games',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='games',
            name='picture',
            field=models.ImageField(upload_to='games/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='price_stars',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в Stars'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='price_ton',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в TON'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advertisers', verbose_name='Рекламодатель'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='limit_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='limit_type',
            field=models.CharField(choices=[('limited', 'Лимитированный'), ('unlimited', 'Безлимитный')], max_length=10, verbose_name='Тип лимита'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='reward',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Награда'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='time_to_complete',
            field=models.IntegerField(verbose_name='Время начисления монет (в часах)'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес кошелька'),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
