# Generated by Django 4.1.13 on 2024-08-17 22:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_purchasescharacters'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='category',
            field=models.CharField(default=1, max_length=255, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
