# Generated by Django 4.1.13 on 2024-08-17 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tasks_category_tasks_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='tasks/', verbose_name='Иконка'),
            preserve_default=False,
        ),
    ]
