# Generated by Django 4.1.13 on 2024-08-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tasks_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='picture_color',
            field=models.CharField(default='#12AAEB', max_length=10, verbose_name='Цвет тени иконки'),
            preserve_default=False,
        ),
    ]
