# Generated by Django 4.1.13 on 2024-08-18 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tasks_picture_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выполнения')),
                ('amount_reward', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма награды')),
                ('status', models.CharField(choices=[('pending', 'Выполняется'), ('awarded', 'Награда получена')], max_length=10, verbose_name='Статус')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tasks', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Выполненное задание',
                'verbose_name_plural': 'Выполненные задания',
            },
        ),
    ]
