# Generated by Django 4.1.13 on 2024-08-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_tasks_limit_count_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='limit_count_reserved',
            field=models.IntegerField(blank=True, default=0, verbose_name='Занято мест'),
        ),
    ]
