# Generated by Django 4.1.13 on 2024-08-20 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_tasks_limit_count_reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='description',
        ),
        migrations.AddField(
            model_name='gamekeys',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.games', verbose_name='Игра'),
            preserve_default=False,
        ),
    ]
