# Generated by Django 4.1.13 on 2024-08-20 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_usedgamekeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamekeys',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
