# Generated by Django 4.1.13 on 2024-08-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_usedgamekeys_amount_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamekeys',
            name='used',
            field=models.BooleanField(default=False, verbose_name='Использован'),
        ),
    ]
