# Generated by Django 4.1.13 on 2024-09-01 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_gamekeys_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество монет')),
                ('start_date', models.DateTimeField(verbose_name='Дата и время старта')),
                ('end_date', models.DateTimeField(verbose_name='Дата и время конца')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Фарминг',
                'verbose_name_plural': 'Фарминги',
            },
        ),
    ]
