# Generated by Django 4.1.13 on 2024-09-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_farmings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Чат ID (для tg)'),
        ),
    ]
