# Generated by Django 4.1.13 on 2024-09-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_tasks_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='chat_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Чат ID (для tg)'),
        ),
    ]
