# Generated by Django 4.1.13 on 2024-09-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_tasks_chat_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='completedtasks',
            index=models.Index(fields=['status'], name='main_comple_status_d0a247_idx'),
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['link'], name='main_tasks_link_48ddc7_idx'),
        ),
    ]
