# Generated by Django 4.1.13 on 2024-09-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_completedtasks_main_comple_status_d0a247_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='balances',
            index=models.Index(fields=['user'], name='main_balanc_user_id_ea7319_idx'),
        ),
        migrations.AddIndex(
            model_name='characters',
            index=models.Index(fields=['type'], name='main_charac_type_6db2db_idx'),
        ),
        migrations.AddIndex(
            model_name='completedtasks',
            index=models.Index(fields=['user'], name='main_comple_user_id_43e9cd_idx'),
        ),
        migrations.AddIndex(
            model_name='completedtasks',
            index=models.Index(fields=['task'], name='main_comple_task_id_6d8623_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['telegram_id'], name='main_custom_telegra_7441f2_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['referral_code'], name='main_custom_referra_c28352_idx'),
        ),
        migrations.AddIndex(
            model_name='farmings',
            index=models.Index(fields=['user'], name='main_farmin_user_id_26eef8_idx'),
        ),
        migrations.AddIndex(
            model_name='gamekeys',
            index=models.Index(fields=['value'], name='main_gameke_value_3c70c8_idx'),
        ),
        migrations.AddIndex(
            model_name='gamekeys',
            index=models.Index(fields=['game'], name='main_gameke_game_id_600f77_idx'),
        ),
        migrations.AddIndex(
            model_name='gamekeys',
            index=models.Index(fields=['used'], name='main_gameke_used_6b11eb_idx'),
        ),
        migrations.AddIndex(
            model_name='games',
            index=models.Index(fields=['name'], name='main_games_name_c1ca63_idx'),
        ),
        migrations.AddIndex(
            model_name='games',
            index=models.Index(fields=['link'], name='main_games_link_623010_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasescharacters',
            index=models.Index(fields=['user'], name='main_purcha_user_id_3ab6b7_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasescharacters',
            index=models.Index(fields=['character'], name='main_purcha_charact_b78c49_idx'),
        ),
        migrations.AddIndex(
            model_name='tariffs',
            index=models.Index(fields=['name'], name='main_tariff_name_3bdb71_idx'),
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['limit_type'], name='main_tasks_limit_t_abc1fd_idx'),
        ),
        migrations.AddIndex(
            model_name='usedgamekeys',
            index=models.Index(fields=['user'], name='main_usedga_user_id_d07d11_idx'),
        ),
        migrations.AddIndex(
            model_name='usedgamekeys',
            index=models.Index(fields=['game_key'], name='main_usedga_game_ke_e3e440_idx'),
        ),
        migrations.AddIndex(
            model_name='wallets',
            index=models.Index(fields=['user'], name='main_wallet_user_id_77d751_idx'),
        ),
    ]
