# Generated by Django 4.1.13 on 2024-09-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_balances_main_balanc_user_id_ea7319_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='is_developing',
            field=models.BooleanField(default=False, verbose_name='В разработке'),
        ),
        migrations.AlterField(
            model_name='games',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка'),
        ),
    ]
