# Generated by Django 5.1.1 on 2024-09-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_games_is_developing_alter_games_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasescharacters',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
